# GitHub Action para gerar um gráfico de contribuição com uma cobra comendo suas contribuições.
name: Generate Datas

on:
    schedule:
        - cron: "* */6 * * *"  # Esta ação ocorre a cada 6 horas.
    workflow_dispatch:  # Executa a ação automaticamente na guia Ações.


jobs:
    build:
        name: Jobs to update datas
        runs-on: ubuntu-latest
        steps:
            # Animação de Cobra
            - uses: Platane/snk@master
            id: snake-gif
            with:
                github_user_name: Miguel-acb9
                svg_out_path: dist/github-contribution-grid-snake.svg

            - uses: crazy-max/ghaction-github-pages@v2.1.3
            with:
                target_branch: output
                build_dir: dist
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
